

name = "ai-chat-assistant"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Workers AI binding
[ai]
binding = "AI"

# Durable Objects
[[durable_objects.bindings]]
name = "CHAT_SESSIONS"
class_name = "ChatSession"
script_name = "ai-chat-assistant"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatSession"]